kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-web
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qotd-web
  template:
    metadata:
      labels:
        app: qotd-web
    spec:
      restartPolicy: Always
      containers:
        - name: qotd-web
          image: registry.gitlab.com/quote-of-the-day/qotd-web/v4.0.0:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENABLE_INSTANA
              value: "false"
            - name: INSTANA_REPORTING_URL
              value: ""
            - name: INSTANA_ENUM_MIN_JS_URL
              value: ""
            - name: INSTANA_KEY
              value: ""
            - name: ANOMALY_GENERATOR_URL
              value: "http://qotd-usecase-{{ .Values.loadNamespace }}.{{ .Values.host }}/services/web"
            - name: QUOTE_SVC
              value: "qotd-quote.qotd.svc.cluster.local:3001"
            - name: AUTHOR_SVC
              value: "qotd-author.qotd.svc.cluster.local:3002"
            - name: IMAGE_SVC
              value: "qotd-image.qotd.svc.cluster.local:3003"
            - name: RATING_SVC
              value: "qotd-rating.qotd.svc.cluster.local:3004"
            - name: PDF_SVC
              value: "qotd-pdf.qotd.svc.cluster.local:3005"
            - name: ENGRAVING_SVC
              value: "qotd-engraving.qotd.svc.cluster.local:3006"

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "50m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "800Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: qotd-web
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: qotd-web
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-web
  namespace: qotd
  labels:
    app: qotd
    tier: web
spec:
  to:
    kind: Service
    name: qotd-web
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
